name: Publish Pages Site

on:
  workflow_dispatch:
  push:
    tags:
      - v*

jobs:
  build:
    name: Publish Pages Site
    runs-on: ubuntu-latest
    env:
      GITHUB_REPOSITORY: ${{ github.repository }}
      GITHUB_REF: ${{ github.ref }}
      GITHUB_SHA: ${{ github.sha }}

    steps:
      - uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3.7.0
      - uses: volta-cli/action@5c175f92dea6f48441c436471e6479dbc192e194 # v4.2.1

      - name: Cache ris4fun compile code
        id: docusaurus-rise4fun-compile-code
        uses: actions/cache@6f8efc29b200d32929f49075959781ed54ec270c # v3.5.0
        with:
          path: website/.docusaurus/docusaurus-remark-plugin-compile-code/
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: yarn install
        run: yarn install --frozen-lockfile

      - name: Build all
        run: yarn build

      - name: Test all
        run: yarn test

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@373f7f263a76c20808c831209c920827a82a2847 # v3.9.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: website/build
          force_orphan: true
