name: Publish Node Packages

on:
    push:
        tags:
            - "v*"

jobs:
    publish:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - uses: volta-cli/action@v1

            - name: yarn install
              run: yarn install --frozen-lockfile

            - name: Build all
              run: yarn build

            - name: Loop through packages and publish
              run: |
                  cd packages
                  for package in $(ls -d */); do
                    echo "Publishing $package..."
                    cd $package
                    echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> .npmrc
                    npm publish
                    cd ..
                  done
