name: Publish Pages Site

on:
  workflow_dispatch:
  push:
    tags:
      - v*

jobs:
  build:
    name: Publish Pages Site
    runs-on: ubuntu-latest
    env:
      GITHUB_REPOSITORY: ${{ github.repository }}
      GITHUB_REF: ${{ github.ref }}
      GITHUB_SHA: ${{ github.sha }}

    steps:
      - uses: actions/checkout@v3
      - uses: volta-cli/action@v4

      - name: Cache ris4fun compile code
        id: docusaurus-rise4fun-compile-code
        uses: actions/cache@v3
        with:
          path: website/.docusaurus/docusaurus-remark-plugin-compile-code/
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: yarn install
        run: yarn install --frozen-lockfile

      - name: Build all
        run: yarn build

      - name: Test all
        run: yarn test

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: website/build
          force_orphan: true
